// ─────────────────────────────────────────────────────────────────────────────
// profile_repository.dart  –  Data access layer for user profile operations.
// ─────────────────────────────────────────────────────────────────────────────

import '../../core/network/api_client.dart';
import '../../core/constants/api_constants.dart';
import '../models/user.dart';

/// Handles fetching and updating the current user's profile via the API.
class ProfileRepository {
  final ApiClient _apiClient;

  ProfileRepository(this._apiClient);

  /// Fetches the current user's profile from the backend.
  ///
  /// Calls GET /api/v1/profile/me (authenticated).
  /// The JWT is automatically attached by the AuthInterceptor in ApiClient.
  ///
  /// Returns a [User] object parsed from the JSON response.
  Future<User> getProfile() async {
    final response = await _apiClient.get(ApiConstants.profile);
    // User.fromJson() is generated by the freezed/json_serializable packages
    return User.fromJson(response.data);
  }

  /// Updates the current user's profile with the provided fields.
  ///
  /// Calls PUT /api/v1/profile/me with only the changed fields.
  /// Fields not included in [profileData] are left unchanged on the server.
  ///
  /// Returns the updated [User] object.
  Future<User> updateProfile(Map<String, dynamic> profileData) async {
    final response = await _apiClient.put(ApiConstants.profile, data: profileData);
    return User.fromJson(response.data);
  }
}
