// ─────────────────────────────────────────────────────────────────────────────
// recommendation.dart  –  Immutable model for a sleep improvement recommendation.
//
// Recommendations are generated by the backend's rule-based insights engine
// and returned from GET /api/v1/insights/recommendations.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:freezed_annotation/freezed_annotation.dart';

part 'recommendation.freezed.dart';
part 'recommendation.g.dart';

/// A single personalised sleep improvement recommendation.
///
/// The [priority] field lets the app sort and colour-code recommendations:
/// - "high"   → Red/urgent, shown at the top
/// - "medium" → Yellow/moderate
/// - "low"    → Green/informational
@freezed
class Recommendation with _$Recommendation {
  const factory Recommendation({
    /// The sleep dimension this recommendation targets.
    /// Examples: "Sleep Efficiency", "Caffeine", "Sleep Duration", "Stress & Mood"
    required String category,

    /// The human-readable advice text shown to the user.
    /// Designed to be actionable and specific (e.g., "Stop screens 30-60 min before bed").
    required String message,

    /// Urgency level: "high", "medium", or "low".
    required String priority,
  }) = _Recommendation;

  /// Creates a [Recommendation] from a JSON map (from the API response).
  factory Recommendation.fromJson(Map<String, dynamic> json) =>
      _$RecommendationFromJson(json);
}
