// ─────────────────────────────────────────────────────────────────────────────
// user.dart  –  Immutable data model for a SmartSleep user account.
//
// This file uses the `freezed` package to generate:
//   - An immutable class with a const constructor
//   - copyWith() method for creating modified copies
//   - == and hashCode implementations
//   - toString() implementation
//
// The `json_serializable` package generates:
//   - fromJson() factory constructor
//   - toJson() method
//
// The generated code lives in:
//   user.freezed.dart  (immutable class boilerplate)
//   user.g.dart        (JSON serialization)
//
// NOTE: Do not edit the .g.dart or .freezed.dart files — they are auto-generated.
// To regenerate: dart run build_runner build
// ─────────────────────────────────────────────────────────────────────────────

import 'package:freezed_annotation/freezed_annotation.dart';

// These `part` directives include the generated files as part of this library
part 'user.freezed.dart';
part 'user.g.dart';

/// Represents a SmartSleep user account.
///
/// All fields except [id] and [email] are optional because users may not
/// have filled in their profile yet. The app prompts them to complete it
/// from the Profile screen.
@freezed
class User with _$User {
  const factory User({
    /// The user's unique identifier (UUID from Supabase).
    /// @JsonKey maps the Dart field name to the JSON key from the backend.
    @JsonKey(name: 'user_id') required String id,

    /// The user's email address (used for login and notifications).
    required String email,

    /// The user's display name (e.g., "John Doe").
    @JsonKey(name: 'full_name') String? fullName,

    /// Whether the user has clicked the confirmation link in their email.
    @JsonKey(name: 'email_confirmed') bool? emailConfirmed,

    /// User's age in years (used for biometric baseline normalisation).
    int? age,

    /// "Male", "Female", or "Other".
    String? gender,

    /// Body weight in kilograms.
    @JsonKey(name: 'weight_kg') double? weightKg,

    /// Height in centimetres.
    @JsonKey(name: 'height_cm') double? heightCm,

    /// ISO 8601 timestamp string when the account was created.
    @JsonKey(name: 'created_at') String? createdAt,
  }) = _User; // `= _User` is freezed syntax for naming the generated impl class

  /// Creates a [User] from a JSON map (e.g., from an API response).
  /// The implementation is generated by json_serializable in user.g.dart.
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
